In [9]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [10]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',None],
      'Age':[None,22,25,27],
      'City':['Pune','Pune',None,'Hyd']}

df1=pd.DataFrame(Data)
df1

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [11]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',Null],
      'Age':[Null,22,25,27],
      'City':['Pune','Pune',Null,'Hyd']}

df2=pd.DataFrame(Data)
df2

NameError: name 'Null' is not defined

In [12]:
df.to_csv('data_Missing.csv',index=False)

In [13]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [14]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [15]:
df.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [16]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [17]:
df.fillna(30) #Not recommended

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [18]:
df['Age'].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [19]:
df1.fillna(30) 

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

- the above one is We are filling randomly
- all the columns are filled with random number
- it is not a good approach because in a data we have different data types

In [20]:
df.fillna('Hyd')

Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

**what is the difference between np.nan and none**

In [21]:
np.nan+5

nan

In [22]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [23]:
arr1

array([ 1.,  2., nan,  3.])

In [24]:
arr2

array([1, 2, None, 3], dtype=object)

In [25]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [26]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents float type
- None represents Object type
- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [27]:
#df.filling()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

**Fill with Methods**
- Whenever we are using methods no need provide values

In [28]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df1=pd.DataFrame(Data)
df1

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

- pad
- bfill
- ffill
- backfill

In [29]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [30]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [31]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [32]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [33]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)

Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

**Mean-Median-Mode**
- instead of filling with random values
- We can use mean median and mode also
- For Numerical columns use mean and median
- if data outliers are there use Median
- 

In [34]:
age_mean=df['Age'].mean()
df['Age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [35]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [36]:
age_mode=df['Age'].mode()
df['Age'].fillna(age_mode)

0    22.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [37]:
age_median

25.0

In [38]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

**KNN Immputer**

- k-Nearest Neighbours
- Where k=hyper parameter which means the user can change
- Idea: Instead of talking all the samples average
  - first fix the neighbours number i.e .k
  - Then find the neighbours using distance metric
  - Then take the average of those samepls to fill the missing value

In [39]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer


In [40]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [42]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2, np.nan], [3,np.nan, 3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(x)


0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [49]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,
                   weights='uniform')
imputer.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [50]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,
                   weights='distance')
imputer.fit_transform(x)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])